#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=logos_ngt_aug
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=5
#SBATCH --time=24:00:00
#SBATCH --output=/home/psobecki/mmaction2/jobs/output/slurm_logos_ngt_aug_%A.txt

module purge
module load 2025

cd $HOME/mmaction2
source .venv/bin/activate

srun python extract_logos_features_pngseq.py \
    --render_dir  /scratch-shared/psobecki/Custom_from_FBX/Saved/Renders \
    --output_dir  $HOME/NGT_Aug/logos_features \
    --checkpoint  $HOME/mmaction2/data/model/logos_autsl_wlasl_model.pth \
    --dataset_name ngt_aug \
    --workers 5 \
    --batch_size 8
