#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=logos_extract
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=5
#SBATCH --time=24:00:00
#SBATCH --output=/home/psobecki/fork_mmaction2/jobs/output/slurm_logos_extract_%A.txt

module purge
module load 2025

cd $HOME/fork_mmaction2
source .venv/bin/activate

srun python extract_logos_features.py \
    --video_dir   /scratch-shared/psobecki/ASL_Citizen/videos \
    --output_dir  $HOME/ASL_Citizen/logos_features_endanchor \
    --checkpoint  $HOME/fork_mmaction2/data/model/logos_autsl_wlasl_model.pth \
    --dataset_name asl_citizen \
    --workers 5 \
    --batch_size 8
