#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=logos_asl_aug
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=5
#SBATCH --time=24:00:00
#SBATCH --output=/home/psobecki/fork_mmaction2/jobs/output/slurm_logos_asl_aug_%A.txt

module purge
module load 2025

cd $HOME/fork_mmaction2
source .venv/bin/activate

srun python extract_logos_features_asl_citizen_aug.py \
    --aug_dir    /scratch-shared/psobecki/asl_citizen/augmented_videos \
    --output_dir /home/psobecki/ASL_Citizen/logos_features \
    --checkpoint $HOME/fork_mmaction2/data/model/logos_autsl_wlasl_model.pth \
    --workers 5 \
    --batch_size 8
#   --overwrite
